#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]"):
    dp = [float('inf')] * (len(a)+2)
    dp[0] = 0
    for i in range(N-2):
        dp[i+1] = min(dp[i+1], dp[i]+abs(a[i]-a[i+1]))
        dp[i+2] = min(dp[i+2], dp[i]+abs(a[i]-a[i+2]))
    return min(dp[N-3]+abs(a[N-3]-a[N-1]), dp[N-2]+abs(a[N-2]-a[N-1]))


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    print(solve(N, a))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
