#!/usr/bin/env python3
import sys


def solve(x: int, y: int, W: str, c: "List[str]"):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    x = int(next(tokens))  # type: int
    y = int(next(tokens))  # type: int
    W = next(tokens)  # type: str
    c = [next(tokens) for _ in range(9)]  # type: "List[str]"
    print(solve(x, y, W, c))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
