#!/usr/bin/env python3
import sys


def f(x):
    ans = chr(x[0] + ord('a') - 1)
    

def solve(N: int):
    '''
    >>> solve(1)
    'a'
    >>> solve(26)
    'z'
    >>> solve(18278)
    'zzz'
    >>> solve(475255)
    'aaaaa'
    '''
    ans = []
    n = N
    while n > 0:
        ans.append((n-1)%26)
        n = (n-1) // 26
    return "".join(map(lambda x: chr(x+ord('a')), reversed(ans)))


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    print(solve(N))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    test()
    main()
