#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]"):
    t, ans = 1, 0
    for h in range(N):
        while t < N and a[t-1] < a[t]:
            t += 1
        ans += t - h
        if t - h == 1:
            t += 1
    return ans

# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    print(solve(N, a))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
