#!/usr/bin/env python3
import sys
from typing import NamedTuple, List

class Game(NamedTuple):
    c: List[int]
    s: List[List[int]]

def solve(D: int, c: "List[int]", s: "List[List[int]]", t: "List[int]"):
    from functools import reduce
    ans = [0]
    lasts = [0] * 26
    adjust = 0
    sum_c = sum(c)
    daily_loss = sum_c
    for day, tt in enumerate(t, 1):
        a = s[day-1][tt-1]
        adjust += day * c[tt-1] - lasts[tt-1] * c[tt-1]
        lasts[tt-1] = day        
        a -= daily_loss
        a += adjust
        ans.append(ans[-1]+a)
        daily_loss += sum_c
    return ans[1:]

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    D = int(next(tokens))  # type: int
    c = [int(next(tokens)) for _ in range(26)]  # type: "List[int]"
    s = [[int(next(tokens)) for _ in range(26)] for _ in range(D)]  # type: "List[List[int]]"
    t = [int(next(tokens)) for _ in range(D)]  # type: "List[int]"
    print(*solve(D, c, s, t), sep="\n")

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
