#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def solve(N: int, s: str):
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    s = next(tokens)  # type: str
    print(solve(N, s))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
