#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    N, M, Q = map(int, input().split())
    solved = [[] for _ in range(N)]
    scores = [N] * M
    for s in (tuple(map(int, input().split())) for _ in range(Q)):
        if s[0] == 1:
            print(sum((scores[p] for p in solved[s[1]-1])))
            continue
        _, n, m = s
        scores[m-1] -= 1
        solved[n-1].append(m-1)

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
