#!/usr/bin/env python3
import sys

def f(n, h):
    w = n // h
    return abs(w-h) + n % h

def solve(n: int):
    ans = float('inf')
    for h in range(1, n+1):
        ans = min(ans, f(n, h))
    return ans


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    n = int(next(tokens))  # type: int
    print(solve(n))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
