#!/usr/bin/env python3

MOD = 2  # type: int


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    N, M = list(map(int, input().split()))
    K, S = [], []
    for _ in range(M):
        t = list(map(int, input().split()))
        K.append(t[0])
        S.append(t[1:])
    p = list(map(int, input().split()))
    def check()

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
