#!/usr/bin/env python3
import sys


def solve(N: int, w: "List[int]"):
    a = [float("inf")] * N
    for ww in w:
        i = min(range(N), key=lambda x: (a[x]<ww, a[x]))
        a[i] = ww
    return sum(aa!=float("inf") for aa in a)


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    w = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    print(solve(N, w))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
