#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    N, M, Q = map(int, input().split())
    edges = [[] for _ in range(N+1)]
    for _ in range(M):
        u, v = map(int, input().split())
        edges[u].append(v)
        edges[v].append(u)
    colors = [0] + list(map(int, input().split()))
    for _ in range(Q):
        s = tuple(map(int, input().split()))
        print(colors[s[1]])
        if s[0] == 2:
            colors[s[1]] = s[2]
            continue
        for n in edges[s[1]]:
            colors[n] = colors[s[1]]

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
