#!/usr/bin/env python3
import sys


def solve(N: int):
    n = N % 10
    if n in [2, 4, 5, 7, 9]:
        return 'hon'
    if n in [0, 1, 6, 8]:
        return 'pon'
    return 'bon'

# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    print(solve(N))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
