#!/usr/bin/env python3
import sys


def solve(N: int):
    if N < 60:
        return 'Bad'
    if N < 90:
        return 'Good'
    if N < 100:
        return 'Great'
    return 'Perfect'


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    print(solve(N))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
