#!/usr/bin/env python3
import sys


def solve(N: int):
    def f(i, h):
        if i == N:
            yield ""
            return
        for c in range(ord('a'), h):
            for s in f(i+1, h):
                yield chr(c) + s
        for s in f(i+1, h+1):
            yield chr(h) + s
    return f(0, ord('a'))


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    print(*solve(N), sep="\n")

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
