#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    a = input()
    print("A" if a.isupper() else "a")

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
