#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str, T: str):
    from collections import defaultdict
    d1 = defaultdict(set)
    d2 = defaultdict(set)
    for s, t in zip(S, T):
        d1[t].add(s)
        d2[s].add(t)
    return YES if max(map(len, d1.values())) < 2 and max(map(len, d2.values())) < 2 else NO

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    print(solve(S, T))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
