#!/usr/bin/env python3
import sys


def solve(M: "List[int]", D: "List[int]"):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    M = [int()] * (2)  # type: "List[int]"
    D = [int()] * (2)  # type: "List[int]"
    for i in range(2):
        M[i] = int(next(tokens))
        D[i] = int(next(tokens))
    print(solve(M, D))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
