#!/usr/bin/env python3
import sys


def solve(s: str):
    from itertools import permutations
    import re
    hands = ["S10,SJ,SQ,SK,SA".split(","),
             "H10,HJ,HQ,HK,HA".split(","),
             "D10,DJ,DQ,DK,DA".split(","),
             "C10,CJ,CQ,CK,CA".split(",")]
    def f():
        for hand in hands:
            for h in permutations(hand):
                m = re.search("(.*)"+"(.*)".join(h), s)
                if m:
                    yield("".join(m.groups()))
    ans = min(f(), key=len)
    return ans if ans else 0

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = next(tokens)  # type: str
    print(solve(s))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
