#!/usr/bin/env python3
import sys


def solve(X: int, Y: int, N: int, t: "List[int]", h: "List[int]"):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    Y = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    t = [int()] * (N)  # type: "List[int]"
    h = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        t[i] = int(next(tokens))
        h[i] = int(next(tokens))
    print(solve(X, Y, N, t, h))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
