#!/usr/bin/env python3
import sys


def solve(A: int, B: int, N: int):
    def f(x):
        return int(A * x / B) - A * int(x / B)
    x = min(N, B-1)
    return f(x)


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    print(solve(A, B, N))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
