#!/usr/bin/env python3
import sys


def solve(N: int, w: "List[int]", h: "List[int]"):
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    w = [int()] * (N)  # type: "List[int]"
    h = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        w[i] = int(next(tokens))
        h[i] = int(next(tokens))
    print(solve(N, w, h))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
