#!/usr/bin/env python3
import sys

def solve(P: float):
    def f(x):
        return P * pow(0.5, x / 1.5) + x
    lb, ub = 0, 10 ** 18 + 1
    while ub - lb > 10 ** -8:
        t1 = (2 * lb + ub) / 3
        t2 = (lb + 2 * ub) / 3
        if f(t1) > f(t2):
            lb = t1
        else:
            ub = t2
    return f((lb + ub) / 2)

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    P = float(next(tokens))  # type: float
    print(solve(P))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
