#!/usr/bin/env python3
import sys


def solve(N: int, M: int, L: int, a: "List[int]", b: "List[int]"):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    L = int(next(tokens))  # type: int
    a = [int()] * (L)  # type: "List[int]"
    b = [int()] * (L)  # type: "List[int]"
    for i in range(L):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    print(solve(N, M, L, a, b))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
