#!/usr/bin/env python3
import sys


def solve(S: int):
    from itertools import takewhile, count
    SS = tuple(map(int, str(S)))
    ans = 0
    t = [0] * 2020
    t[0] = 1
    u, cnt = 0, 0
    for i, n in enumerate(reversed(SS)):
        u = (n * pow(10, i, 2019) + u) % 2019
        cnt += t[u]
        t[u] += 1
    return cnt



# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = int(next(tokens))  # type: int
    print(solve(S))

if __name__ == '__main__':
    main()
