#!/usr/bin/env python3

def solve(N, K, A):
    ind = []
    tr = None
    visited = set()
    cur = 1
    while cur not in visited:
        ind.append(cur)
        visited.add(cur)
        cur = A[cur-1]
    tr = cur
    itr = ind.index(tr)
    if len(ind) > K:
        return ind[K]
    KK = K - itr
    iind = ind[itr:]
    return iind[KK%len(iind)]

        


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    N, K = map(int, input().split())
    A = tuple(map(int, input().split()))
    print(solve(N, K, A))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
