#!/usr/bin/env python3
import sys


def solve(N: int):
    from itertools import takewhile, count
    dp = list(range(N+1))
    for n in (6, 9):
        for m in takewhile(lambda x: x<=N, (n**e for e in count(1))):
            for i in range(m, N+1):
                dp[i] = min(dp[i], dp[i-m]+1)
    return dp[N]


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    print(solve(N))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
