#!/usr/bin/env python3
import sys


def solve(N: int, a: int, k: str, b: "List[int]"):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = int(next(tokens))  # type: int
    k = next(tokens)  # type: str
    b = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    print(solve(N, a, k, b))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
