#!/usr/bin/env python3

YES = "Possible"  # type: str
NO = "Impossible"  # type: str


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    # Failed to predict input format
    pass

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
