#!/usr/bin/env python3
import sys


def solve(K: int, S: str):
    '''
    >>> solve(1, 'a')
    'a'
    '''
    if len(S) <= K:
        return S
    return S[:K] + '...'


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    print(solve(K, S))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    test()
    main()
