#!/usr/bin/env python3
import sys


def solve(N: int, K: int, h: "List[int]"):
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    h = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    print(solve(N, K, h))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
