#!/usr/bin/env python3
import sys


def solve(c: "List[str]"):
    return c[0][0] + c[1][1] + c[2][2]


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    c = [next(tokens) for _ in range(3)]  # type: "List[str]"
    print(solve(c))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
