#!/usr/bin/env python3


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    A = map(int, input().split())
    B = filter(lambda x: x%2==0, A)
    print('APPROVED' if all(map(lambda x: x%3==0 or x%5==0, B)) else 'DENIED')

if __name__ == '__main__':
    main()
