#!/usr/bin/env python3
import sys

YES = "YES"  # type: str
NO = "NO"  # type: str


def solve(N: int, NG: "List[int]"):
    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    NG = [int(next(tokens)) for _ in range(3)]  # type: "List[int]"
    print(solve(N, NG))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
