#!/usr/bin/env python3
import sys

def factor_iter(n):
    from itertools import takewhile
    m = n
    for p in range(2, int(n**0.5)+2):
        while m % p == 0:
            yield p
            m //= p
        if m == 1:
            return
    if m != 1:
        yield m

def f(c):
    ret = 0
    tmp = 1
    while c >= tmp:
        c -= tmp
        ret += 1
        tmp += 1
    return ret

def solve(N: int):
    from collections import Counter
    p = Counter(factor_iter(N))
    return sum(map(f, p.values()))

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    print(solve(N))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
