#!/usr/bin/env python3
import sys


def solve(P: int, Q: int, R: int):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    P = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    print(solve(P, Q, R))

def test():
    import doctest
    doctest.testmod()

if __name__ == '__main__':
    #test()
    main()
